export const APP_ROUTES = {
  root: '/',
  login: '/login',
  dashboard: '/',
  employees: '/colaboradores',
  ingredients: '/ingredientes',
  production: '/producao',
  breadControl: '/controle-paes',
  wasteControl: '/controle-desperdicio',
  schedule: '/escala',
  cleaningSchedule: '/escala-limpeza',
  recipes: '/receitas',
  comments: '/comentarios',
  pop: '/pop',
  changePassword: '/alterar-senha',
  intelligence: '/intelligence',
  nannaiInsights: '/nannai-insights',
  audit: '/auditoria',
  labels: '/etiquetas',
  niimbot: '/niimbot',
  niimbotSettings: '/niimbot/configuracoes',
  niimbotPrintTest: '/niimbot/teste',
  laboratorio: '/laboratorio-nannai',
  devCentral: '/central-desenvolvedor',
  advancedSettings: '/configuracoes-avancadas',
  bugs: '/central-bugs',
  notFound: '*',
} as const

export type AppRouteKey = keyof typeof APP_ROUTES
